name: Aux workflow

on:
  workflow_run:
    workflows: ["Main tests"]
    types:
      - completed

env:
  app: "Accept:application/vnd.github.v3+json"

jobs:
  job1:
    name: job 1
    runs-on: ubuntu-20.04

    steps:
    - name: cache
      uses: actions/cache@v2
      with:
        path: cache_file
        key: auto-comment2

    - name: See cache sharing with main
      run: |
        echo "GITHUB_REF is $GITHUB_REF"
        cat cache_file
        comment=$(cat cache_file)
        echo $comment
        curl -sS -X POST -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" -H "$app" https://api.github.com/repos/MinsukJi-NOAA/workflow_test/issues/1/comments -d '{"body": "'"${comment}"'"}'
