name: Aux workflow

on:
  workflow_run:
    workflows: ["Main tests"]
    types:
      - completed

jobs:
  job1:
    name: job 1
    runs-on: ubuntu-20.04

    steps:
    - name: See cache sharing with main
      run: |
        cat cache_file
