name: Aux workflow

on:
  workflow_run:
    workflows: ["Main tests"]
    types:
      - completed

env:
  app: "Accept:application/vnd.github.v3+json"

jobs:
  job1:
    name: job 1
    runs-on: ubuntu-20.04

    steps:
    - name: cache
      uses: actions/cache@v2
      with:
        path: cf
        key: 20210411-3

    - name: use cache 1
      run: cat cf

    - name: cache 2
      uses: actions/cache@v2
      with:
        path: cf
        key: 20210411-4

    - name: use cache 2
      run: cat cf
#    - name: See cache sharing with main
#      run: |
#        echo "GITHUB_REF is $GITHUB_REF"
#        cat comment_file
#        comment=$(cat comment_file)
#        echo $comment
#        curl -sS -X POST -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" -H "$app" https://api.github.com/repos/MinsukJi-NOAA/workflow_test/issues/2/comments -d '{"body": "'"${comment}"'"}'
