name: Main tests

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  job1:
    name: job 1
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: cache
      id: cache-file
      uses: actions/cache@v2
      with:
        path: ~/cache_file
        key: main-cache

    - name: generate cache file
      if: steps.cache-file.outputs.cache-hit != 'true'
      run: echo "Hello, World!" >> ~/cache_file

    - name: use cache
      run: cat ~/cache_file

  job2:
    name: job 2
    runs-on: ubuntu-20.04

    steps:
    - name: use cache in job 2
      run: cat ~/cache_file
