name: Main tests

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  apiApp: "Accept: application/vnd.github.v3+json"

jobs:
  job1:
    name: job 1
    runs-on: ubuntu-20.04

    steps:
    - name: Print out global env var
      run: |
        echo $apiApp
        echo ${{ env.apiApp }}

  job2:
    name: job 2
    runs-on: ubuntu-20.04

    steps:
    - name: Print out global env var
      run: |
        echo $apiApp
        echo ${{ env.apiApp }}
