name: Main tests

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  app: "Accpet:application/vnd.github.v3+json"

jobs:
  job1:
    name: job 1
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: generate comments
      run: comment="This is extensive commit message\n\n* item 1;\n* item 2;\n* item 3"

    - name: cache
      id: cache-file
      uses: actions/cache@v2
      with:
        path: cache_file
        key: ${{runner.os}}

    - name: generate cache file
      if: steps.cache-file.outputs.cache-hit != 'true'
      run: printf %s "$comment" >> cache_file

    - name: use cache
      run: cat cache_file

  job2:
    name: job 2
    runs-on: ubuntu-20.04
    needs: job1

    steps:
    - name: cache
      uses: actions/cache@v2
      with:
        path: cache_file
        key: ${{runner.os}}

    - name: use cache in job 2
      run: |
        cat cache_file
