name: Main tests

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  app: "Accept: application/vnd.github.v3+json"

jobs:
  job1:
    name: job 1
    runs-on: ubuntu-20.04

    steps:
    - name: Print out global env var
      run: |
        echo $app
        curl -sS -H $app https://api.github.com/repos/MinsukJi-NOAA/ufs-weather-model/pulls

  job2:
    name: job 2
    runs-on: ubuntu-20.04

    steps:
    - name: Print out global env var
      run: |
        echo $app
        curl -sS -H $app https://api.github.com/repos/MinsukJi-NOAA/ufs-weather-model/pulls
